In [1]:
# TENSORFLOW

import tensorflow as tf
import numpy as np

In [62]:
a=tf.constant(15)
b=tf.constant(20)

In [64]:
print(a*b)

tf.Tensor(300, shape=(), dtype=int32)


In [66]:
x=np.random.rand(100).astype(np.float32)

In [68]:
print(x)

[0.32424217 0.67685324 0.08497392 0.43822378 0.96705097 0.5052016
 0.3194278  0.6429024  0.6723605  0.5448016  0.64792156 0.10722195
 0.6915311  0.9100323  0.35145402 0.21356367 0.84381294 0.7669899
 0.8368033  0.82238287 0.751457   0.34242225 0.73969674 0.7323974
 0.24570394 0.33463582 0.7653292  0.4187664  0.14153601 0.77413476
 0.3353405  0.01438131 0.92708665 0.46406657 0.5340173  0.77186406
 0.73846084 0.73420155 0.42110372 0.72510535 0.4267371  0.11721191
 0.52393377 0.36089677 0.2893176  0.03929205 0.05841864 0.5439215
 0.80009365 0.9748147  0.02446825 0.28597492 0.28660902 0.36515927
 0.21260862 0.51779264 0.38378835 0.9811827  0.24634622 0.4115426
 0.30477226 0.79666567 0.48824722 0.70328474 0.40302044 0.7310337
 0.6614046  0.63928473 0.8914148  0.32294935 0.4605994  0.87638307
 0.4053896  0.3866805  0.35985395 0.58609486 0.84102875 0.5526312
 0.39870155 0.18206395 0.3958607  0.01102979 0.9317731  0.42288777
 0.13350318 0.57965255 0.27459952 0.5751406  0.5167251  0.5224693
 0.

In [70]:
y=0.2*x+0.2

In [72]:
W=tf.Variable(tf.random.normal([1]))

In [74]:
b=tf.Variable(tf.zeros([1]))

In [76]:
def mse_loss():
    # Ensure all variables are float tensors
    y_pred = W * tf.cast(x, tf.float32) + b
    loss = tf.reduce_mean(tf.square(y_pred - tf.cast(y, tf.float32)))
    return loss


In [78]:
optimizer=tf.optimizers.Adam()

In [80]:
for step in range(5000):
    with tf.GradientTape() as tape:
        # Compute the loss within the gradient tape context
        loss = mse_loss()

    # Calculate gradients with respect to W and b
    gradients = tape.gradient(loss, [W, b])
    
    # Apply gradients to update W and b
    optimizer.apply_gradients(zip(gradients, [W, b]))
    
    # Print progress every 500 steps
    if step % 500 == 0:
        print(step, W.numpy(), b.numpy())

0 [0.061434] [0.00099999]
500 [0.23069488] [0.18249077]
1000 [0.21708418] [0.19053468]
1500 [0.20696567] [0.19614078]
2000 [0.20199902] [0.1988925]
2500 [0.20037167] [0.19979408]
3000 [0.2000398] [0.19997796]
3500 [0.20000234] [0.19999872]
4000 [0.20000112] [0.19999936]
4500 [0.20000084] [0.19999953]


In [81]:
# PYTORCH


import torch
import numpy as np

In [84]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [86]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [88]:
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [90]:
print(type(x_np))

<class 'torch.Tensor'>


In [92]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [94]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[0.7829, 0.9927],
        [0.9144, 0.3911]])


In [96]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.2952, 0.0453, 0.0787],
        [0.2169, 0.3242, 0.2623]])
<class 'torch.Tensor'>


In [98]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>


In [100]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [110]:
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.4978, 0.9581, 0.8121, 0.1011],
        [0.2384, 0.6527, 0.1379, 0.4835],
        [0.2518, 0.4634, 0.8754, 0.5226]])


device(type='cpu')

In [128]:
tensor = torch.ones(4,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [130]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [132]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [120]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
tensor.add_(3)
print(tensor)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [124]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [126]:
n = t.numpy()
print(n)
print(type(n))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
